#' --------------------------------------
#' title: run_simulation.R
#' author: Ruth Corona-Moreno
#' description: 
#' The script performed simulations of the mathematical compartmental discrete model proposed in the thesis:
#' "Un modelo matemático para el análisis de la epidemia por COVID-19 tras la reapertura de escuelas en Querétaro"
#' https://tesiunam.dgb.unam.mx/F/JMEPIAMGH6XAFC3YYPMLH8E8HGE58GH7TFRBVGTMKPJ31I9JF3-50871?func=find-b&local_base=TES01&request=covid19+quer%C3%A9taro&find_code=WRD&adjacent=N&filter_code_2=WYR&filter_request_2=&filter_code_3=WYR&filter_request_3=
#'
#' input parameters:
#' --------------------------------------
#' --lugar.name[string]        location name assigned in the .csv file located in "data/Estimations_2021-09-26" folder, which includes the estimations made by NoMAA
#' --pop_tot[int]              total population of "lugar.name"
#' --vac[string]     		       vaccination status of school population: "YES"/"NO"
#' --esc.size[int]             total population in the school
#' --TP0inic[int]              initial condition of True Positive population compartment
#' --FP0inic[int]              initial condition of False Positive population compartment
#' --D0inic[int]               initial condition of Death population compartment
#' --S0inic[int]               initial condition of Symptomatic population compartment
#' --Rec0inic[int]             initial condition of Recovered population compartment
#' --ci[int]                   initial condition of Asymptomatic and Symptomatic population compartment (both will be the same)
#' --estimations_date['Y-m-d'] string date in "data/Estimation_Y-m-m" folder
#' --TimeWindow[int]           Time window to simulate external epidemic data: 1='2020-08-02' to '2020-12-17'// 2='2021-03-05' to '2021-07-20' // 3='2021-05-01' to '2021-09-15'
#' --type.test[int]            Screening strategy considered in school: 1=Constant //2=Lineal //3=quotient
#' --tau[float]                Initial proportion of total population school tested
#' --tau.ext[float]            proportion of population tested outside school
#' --Sp[float]                 percentage of specificity of tests (decimal)
#' --Se[float]                 percentage of sensibility of tests (decimal)
#' --b.esc[float]              probability of effective contact outside school
#' --w[float]                  fixed proportion of lost of immunity
#' --phi[float]                fixed proportion of false positive individual becoming susceptible again
#'
#' Output
#' --------------------------------------
#' 1) File: paste("output/",lugar.name,"_",inic_esc,"_",fin_esc,"_Vac",vac,"_bEsc",b.esc,"_Tot",esc.size,"_w",w,"_Test",type.test,"_tau",tau,"_A0E0",ci,".csv", sep=""))
#' 2) Plot type plotly 
#' 
#' Dependencies from base R:
#' --------------------------------------
#' 1) dplyr
#' 2) interp
#' 3) tidyr
#' 4) plotly
#' 
#' Databases required:
#' --------------------------------------
#' data/Estimations_2021-09-26.csv   Provided by Nodo Multidisciplinario de Matemáticas Aplicadas (NoMAA), IMUNAM
#' output/DistProb_VacYES.csv        Generated by "run_distributions.R" code
#'
#' Dependencies from codes in this repository:
#' --------------------------------------
#' 1) codes/R/functions/fun_simulations.R
#'
#' Addtional notes:
#' --------------------------------------
#' The database "output/DistProb_VacYES.csv" corresponds to a university population, defined by age in the "run_distributions.R" code


library(dplyr) 
library(interp)
library(tidyr) 
library(plotly)
source("codes/R/functions/fun_simulations.R", local = TRUE)


#*************************************************************************
#------------------------Set parameters values----------------------------

#Location name and total population
lugar.name <- 'QUERETARO_CAP'
pop_tot <- 1.05*(10^6)

#School population initial conditions
vac <- 'YES'
esc.size <- 1000
TP0inic <-  0 
FP0inic <- 0
D0inic <- 0
S0inic <- 0 
Rec0inic <- 8
ci <- 3 #E0inic=A0inic=ci

#Estimations from covidestim
estimations_date <- '2021-09-26'
TimeWindow <- 3

#Vaccination conditions
type.test <- 3
tau <- 0.05
tau.ext <- 0
Sp <- 0.97
Se <- 0.80

#Parameters of the model
b.esc <- 0.1
w <- 0
phi <- 0.3
TauMax=esc.size/2 #Required to define the linear screening strategy


#*************************************************************************
#------------------------Time windows definition---------------------------
if(TimeWindow==1){
  inic_esc='2020-08-02'
  fin_esc= '2020-12-17'
}else if(TimeWindow==2){
  inic_esc='2021-03-05'
  fin_esc= '2021-07-20'
}else if(TimeWindow==3){
  inic_esc='2021-05-01'
  fin_esc= '2021-09-15'
}else{
  print("Error")
}


#*************************************************************************
#--------------------------Making simulations-----------------------------
x <- modelo_func(
  vacuna=vac,
  b.esc=b.esc,
  lugar=lugar.name,
  esc.size =esc.size,
  w=w,
  type.test=type.test,
  tau=tau,
  A0inic=ci, 
  E0inic=ci 
)

#Saving simulations
df_simulations <- data.frame(x$fechas_simul,x$x.simul.Simul.U, x$simul.E, x$simul.A, x$simul.TP, x$simul.FP, x$simul.S, x$simul.R, x$simul.D, x$simul.beta.v, x$simul.rt_esc, x$simul.tests)
write.csv(df_simulations, paste("output/",lugar.name,"_",inic_esc,"_",fin_esc,"_Vac",vac,"_bEsc",b.esc,"_Tot",esc.size,"_w",w,"_Test",type.test,"_tau",tau,"_A0E0",ci,".csv", sep=""))


#Plot simulations
plot_func(lugar.name, inic_esc, fin_esc, vac, b.esc, esc.size, w, type.test, tau, ci)
